In [1]:
import pandas as pd
import numpy as np
import requests

In [2]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [3]:
response

In [5]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 132.058,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'title': 'The Shawshank Redemption',
   'video': False,
   'vote_average': 8.706,
   'vote_count': 26438},
  {'adult': False,
   'backdrop_path': '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 133.796,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'title': 'The Godfather',
   'video': False,
   'vote_average': 8.692,
   'vote_count': 20076},
  {'adult': False,
   'backdrop_path': '/b6w7gKLQLS2zw4JK0XmKgQ4gnzr.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 100.069,
   'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
   'release_date': '1974-12-20',
   'title': 'The Godfather Part II',
   'video': False,
   'vote_average': 8.6,
   'vote_count': 12108},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 88.031,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'title': "Schindler's List",
   'video': False,
   'vote_average': 8.567,
   'vote_count': 15515},
  {'adult': False,
   'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
   'genre_ids': [18],
   'id': 389,
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 98.578,
   'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
   'release_date': '1957-04-10',
   'title': '12 Angry Men',
   'video': False,
   'vote_average': 8.543,
   'vote_count': 8354},
  {'adult': False,
   'backdrop_path': '/m4TUa2ciEWSlk37rOsjiSIvZDXE.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 104.037,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'title': 'Spirited Away',
   'video': False,
   'vote_average': 8.537,
   'vote_count': 16102},
  {'adult': False,
   'backdrop_path': '/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 62.514,
   'poster_path': '/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg',
   'release_date': '1995-10-20',
   'title': 'Dilwale Dulhania Le Jayenge',
   'video': False,
   'vote_average': 8.536,
   'vote_count': 4404},
  {'adult': False,
   'backdrop_path': '/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
   'genre_ids': [18, 28, 80, 53],
   'id': 155,
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 130.472,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'title': 'The Dark Knight',
   'video': False,
   'vote_average': 8.516,
   'vote_count': 32197},
  {'adult': False,
   'backdrop_path': '/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 110.695,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'title': 'Parasite',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 17742},
  {'adult': False,
   'backdrop_path': '/vxJ08SvwomfKbpboCWynC3uqUg4.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 93.813,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'title': 'The Green Mile',
   'video': False,
   'vote_average': 8.506,
   'vote_count': 16977},
  {'adult': False,
   'backdrop_path': '/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg',
   'genre_ids': [16, 10749, 18],
   'id': 372058,
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 112.464,
   'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
   'release_date': '2016-08-26',
   'title': 'Your Name.',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 11089},
  {'adult': False,
   'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
   'genre_ids': [53, 80],
   'id': 680,
   'original_language': 'en',
   'original_title': 'Pulp Fiction',
   'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
   'popularity': 95.404,
   'poster_path': '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
   'release_date': '1994-09-10',
   'title': 'Pulp Fiction',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 27348},
  {'adult': False,
   'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 125.538,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-01',
   'title': 'The Lord of the Rings: The Return of the King',
   'video': False,
   'vote_average': 8.481,
   'vote_count': 23610},
  {'adult': False,
   'backdrop_path': '/mzfx54nfDPTUXZOG48u4LaEheDy.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 13,
   'original_language': 'en',
   'original_title': 'Forrest Gump',
   'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
   'popularity': 95.783,
   'poster_path': '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
   'release_date': '1994-06-23',
   'title': 'Forrest Gump',
   'video': False,
   'vote_average': 8.475,
   'vote_count': 26863},
  {'adult': False,
   'backdrop_path': '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg',
   'genre_ids': [37],
   'id': 429,
   'original_language': 'it',
   'original_title': 'Il buono, il brutto, il cattivo',
   'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
   'popularity': 75.399,
   'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
   'release_date': '1966-12-22',
   'title': 'The Good, the Bad and the Ugly',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 8365},
  {'adult': False,
   'backdrop_path': '/d6UxFCGQxpszcf8mwgGjQ3ynqGl.jpg',
   'genre_ids': [18, 80],
   'id': 769,
   'original_language': 'en',
   'original_title': 'GoodFellas',
   'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
   'popularity': 70.141,
   'poster_path': '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
   'release_date': '1990-09-12',
   'title': 'GoodFellas',
   'video': False,
   'vote_average': 8.463,
   'vote_count': 12543},
  {'adult': False,
   'backdrop_path': '/gwj4R8Uy1GwejKqfofREKI9Jh7L.jpg',
   'genre_ids': [16, 18, 10752],
   'id': 12477,
   'original_language': 'ja',
   'original_title': '火垂るの墓',
   'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
   'popularity': 0.058,
   'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg',
   'release_date': '1988-04-16',
   'title': 'Grave of the Fireflies',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 5312},
  {'adult': False,
   'backdrop_path': '/bxSBOAD8AuMHYMdW3jso9npAkgt.jpg',
   'genre_ids': [10751, 18],
   'id': 667257,
   'original_language': 'es',
   'original_title': 'Cosas imposibles',
   'overview': 'After the death of her abusive husband, Matilde finds her new best friend in Miguel, her young, insecure, and disoriented neighbor.',
   'popularity': 13.296,
   'poster_path': '/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg',
   'release_date': '2021-06-17',
   'title': 'Impossible Things',
   'video': False,
   'vote_average': 8.459,
   'vote_count': 379},
  {'adult': False,
   'backdrop_path': '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg',
   'genre_ids': [28, 18],
   'id': 346,
   'original_language': 'ja',
   'original_title': '七人の侍',
   'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
   'popularity': 63.258,
   'poster_path': '/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg',
   'release_date': '1954-04-26',
   'title': 'Seven Samurai',
   'video': False,
   'vote_average': 8.458,
   'vote_count': 3547},
  {'adult': False,
   'backdrop_path': '/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg',
   'genre_ids': [35, 18],
   'id': 637,
   'original_language': 'it',
   'original_title': 'La vita è bella',
   'overview': 'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.',
   'popularity': 57.716,
   'poster_path': '/74hLDKjD5aGYOotO6esUVaeISa2.jpg',
   'release_date': '1997-12-20',
   'title': 'Life Is Beautiful',
   'video': False,
   'vote_average': 8.451,
   'vote_count': 12799}],
 'total_pages': 475,
 'total_results': 9495}

In [17]:
df = pd.DataFrame(response.json()['results'])

In [18]:
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,132.058,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.706,26438
1,False,/tmU7GeKVybMWFButWEGl2M4GeiP.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",133.796,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.692,20076
2,False,/b6w7gKLQLS2zw4JK0XmKgQ4gnzr.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,100.069,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.600,12108
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,88.031,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.567,15515
4,False,/qqHQsStV6exghCM7zbObuYBiYxw.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,98.578,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.543,8354
5,False,/m4TUa2ciEWSlk37rOsjiSIvZDXE.jpg,"[16, 10751, 14]",129,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",104.037,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,Spirited Away,False,8.537,16102
6,False,/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg,"[35, 18, 10749]",19404,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",62.514,/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg,1995-10-20,Dilwale Dulhania Le Jayenge,False,8.536,4404
7,False,/dqK9Hag1054tghRQSqLSfrkvQnA.jpg,"[18, 28, 80, 53]",155,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.472,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,The Dark Knight,False,8.516,32197
8,False,/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg,"[35, 53, 18]",496243,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",110.695,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,Parasite,False,8.500,17742
9,False,/vxJ08SvwomfKbpboCWynC3uqUg4.jpg,"[14, 18, 80]",497,en,The Green Mile,A supernatural tale set on death row in a Sout...,93.813,/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg,1999-12-10,The Green Mile,False,8.506,16977
10,False,/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg,"[16, 10749, 18]",372058,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,112.464,/q719jXXEzOoYaps6babgKnONONX.jpg,2016-08-26,Your Name.,False,8.500,11089
11,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,"[53, 80]",680,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",95.404,/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg,1994-09-10,Pulp Fiction,False,8.500,27348
12,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,en,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,125.538,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-01,The Lord of the Rings: The Return of the King,False,8.481,23610
13,False,/mzfx54nfDPTUXZOG48u4LaEheDy.jpg,"[35, 18, 10749]",13,en,Forrest Gump,A man with a low IQ has accomplished great thi...,95.783,/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg,1994-06-23,Forrest Gump,False,8.475,26863
14,False,/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg,[37],429,it,"Il buono, il brutto, il cattivo",While the Civil War rages on between the Union...,75.399,/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg,1966-12-22,"The Good, the Bad and the Ugly",False,8.500,8365
15,False,/d6UxFCGQxpszcf8mwgGjQ3ynqGl.jpg,"[18, 80]",769,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",70.141,/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg,1990-09-12,GoodFellas,False,8.463,12543
16,False,/gwj4R8Uy1GwejKqfofREKI9Jh7L.jpg,"[16, 18, 10752]",12477,ja,火垂るの墓,"In the final months of World War II, 14-year-o...",0.058,/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg,1988-04-16,Grave of the Fireflies,False,8.500,5312
17,False,/bxSBOAD8AuMHYMdW3jso9npAkgt.jpg,"[10751, 18]",667257,es,Cosas imposibles,"After the death of her abusive husband, Matild...",13.296,/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg,2021-06-17,Impossible Things,False,8.459,379
18,False,/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg,"[28, 18]",346,ja,七人の侍,A samurai answers a village's request for prot...,63.258,/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg,1954-04-26,Seven Samurai,False,8.458,3547
19,False,/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg,"[35, 18]",637,it,La vita è bella,A touching story of an Italian book seller of ...,57.716,/74hLDKjD5aGYOotO6esUVaeISa2.jpg,1997-12-20,Life Is Beautiful,False,8.451,12799

In [19]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [20]:
temp_df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,132.058,8.706,26438
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,133.796,8.692,20076
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,100.069,8.600,12108
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,88.031,8.567,15515
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,98.578,8.543,8354
5,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,104.037,8.537,16102
6,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,62.514,8.536,4404
7,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,130.472,8.516,32197
8,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,110.695,8.500,17742
9,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,93.813,8.506,16977
10,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,112.464,8.500,11089
11,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,95.404,8.500,27348
12,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-01,125.538,8.481,23610
13,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,95.783,8.475,26863
14,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-22,75.399,8.500,8365
15,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,70.141,8.463,12543
16,12477,Grave of the Fireflies,"In the final months of World War II, 14-year-o...",1988-04-16,0.058,8.500,5312
17,667257,Impossible Things,"After the death of her abusive husband, Matild...",2021-06-17,13.296,8.459,379
18,346,Seven Samurai,A samurai answers a village's request for prot...,1954-04-26,63.258,8.458,3547
19,637,Life Is Beautiful,A touching story of an Italian book seller of ...,1997-12-20,57.716,8.451,12799

In [22]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [25]:
for i in range(1, 429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = df.append(temp_df, ignore_index = True)

AttributeError: 'DataFrame' object has no attribute 'append'

In [26]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = df.append(temp_df,ignore_index=True)

AttributeError: 'DataFrame' object has no attribute 'append'

In [27]:
df_list = []
for i in range(1, 429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df_list.append(temp_df)

df = pd.concat(df_list, ignore_index=True)
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,132.058,8.706,26438
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,133.796,8.692,20076
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,100.069,8.600,12108
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,88.031,8.567,15515
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,98.578,8.543,8354
...,...,...,...,...,...,...,...
8555,9327,The Nutty Professor,When beautiful Carla Purty joins the universit...,1996-06-28,32.361,5.600,2818
8556,373314,Misconduct,An ambitious lawyer finds himself caught in a ...,2016-02-05,13.095,5.600,551
8557,18480,Brüno,Flamboyantly gay Austrian television reporter ...,2009-07-08,12.952,5.628,1658
8558,659986,The Owners,A group of friends think they found the perfec...,2020-08-27,15.072,5.627,366
8559,72559,G.I. Joe: Retaliation,"Framed for crimes against the country, the G.I...",2013-03-27,53.321,5.600,5370

In [28]:
df.describe()

                 id   popularity  vote_average    vote_count
count  8.560000e+03  8560.000000   8560.000000   8560.000000
mean   1.927537e+05    38.947793      6.795769   2086.011215
std    2.567301e+05   102.943949      0.635844   3237.102673
min    2.000000e+00     0.046000      5.600000    300.000000
25%    9.906750e+03    17.934750      6.294000    475.000000
50%    3.408750e+04    28.032000      6.761000    885.000000
75%    3.535695e+05    43.681750      7.269250   2113.250000
max    1.212073e+06  7738.120000      8.706000  35987.000000

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8560 entries, 0 to 8559
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            8560 non-null   int64
 1   title         8560 non-null   object
 2   overview      8560 non-null   object
 3   release_date  8560 non-null   object
 4   popularity    8560 non-null   float64
 5   vote_average  8560 non-null   float64
 6   vote_count    8560 non-null   int64
dtypes: float64(2), int64(2), object(3)
memory usage: 468.3+ KB

In [30]:
df.to_csv('movie_data.csv')